### ISSUE TITLE
No date and time under "Completed At:" for Quotes

### ISSUE THREAD

**Issue by SKVetr** [snax4a/service-quotes-web#15]
What are the preconditions to reproduce this issue?
-------------------------------------------
1. There is completed service request in the system

What are the steps to reproduce this issue?
-------------------------------------------
1. Log in on customer account with Quote
2. Enter Quote details

What happens?
-------------
Service Request details on the right side of the screen are missing date and time under "Completed At:".

What were you expecting to happen?
----------------------------------
Date and time present under "Completed At:"..

Any logs, error output, etc?
----------------------------

![Issue](https://user-images.githubusercontent.com/48091419/129105875-c5519942-5ddd-4ea8-8f3f-c37915194d0a.jpg)

Notes?
-------------------
None.

**Comment by snax4a** [comment]
@SKVetr This one was fixed and completed at is filled in for all new service requests.
Only the old services which were created before fix have this field empty.
You can see Completed At filled here: https://service-quotes-web.vercel.app/quotes/302e0d27-1e0e-4ceb-b62c-47759b14a5b1

**Comment by SKVetr** [comment]
Fix Verified.
**New** Quotes created have Completed At correctly filled.
