### ISSUE TITLE
Unexpected error when Customer attempts to access not owned or not existing address

### ISSUE THREAD

**Issue by SKVetr** [snax4a/service-quotes-web#23]
What are the steps to reproduce this issue?
-------------------------------------------
1. Log in on customer account
2. Attempt to access an address details page via direct URL with not existing ID

OR

1. Log in on customer account
2. Attempt to access an address details page via direct URL with valid ID that is not owned

What happens?
-------------
An unexpected error occurs.

What were you expecting to happen?
----------------------------------
Info about address not found.
Or redirect to list page.

Any logs, error output, etc?
----------------------------

![Issue](https://user-images.githubusercontent.com/48091419/129237863-67555d2a-5d05-4caa-baba-1e3d74e1dc86.jpg)

Notes?
-------------------
Example of invalid ID URL: [/addresses/0ae9ac1b](https://service-quotes-web.vercel.app/addresses/0ae9ac1b)

**Comment by snax4a** [comment]
This was already fixed in related issue #25
