### ISSUE TITLE
Infinite loading when Manager account attempts to access account details page with not existing ID

### ISSUE THREAD

**Issue by SKVetr** [snax4a/service-quotes-web#26]
What are the steps to reproduce this issue?
-------------------------------------------
1. Log in on manager account
2. Attempt to access a account details via direct URL with invalid ID

What happens?
-------------
A page with loading icon is displayed.
Appears to be infinitely loading.

What were you expecting to happen?
----------------------------------
Info about account not found.

Any logs, error output, etc?
----------------------------

![Issue](https://user-images.githubusercontent.com/48091419/129242333-41575335-dc4b-4a62-b83f-bced08929b1f.jpg)

Notes?
-------------------
Example of URL with invalid ID: [/accounts/7542b6](https://service-quotes-web.vercel.app/accounts/7542b6)

**Comment by snax4a** [comment]
This was already fixed in related issue #25
